# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b88f8951c3277891cda0d588f5993b0c89ea67d2fbbdf576b96cbc6485adf3c7d57e41d449a63b3a01a88d47e626f9eb05f32967eba84bde04ef05da1ad532e

test:
  secret_key_base: 961268101adf584aa18e236469620433d5d02c178888c748bb8884c33cc0a656dde819becb1e61d19bd7fc824fa1f9380b6398a543163ff5035791d9a3d87d61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
